sudo: required
dist: trusty

language: python
python:
  - "3.5"

notifications:
  email: false

services:
  - postgresql
addons:
  postgresql: "9.5"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p "$HOME/miniconda"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes --quiet conda

install:
  - conda env create --quiet --name app --file config/environment.yml
  - sudo -u postgres psql < config/setup.sql
  - source config/settings.test

before_script:
  - conda env export
  - psql --version

script:
  - flake8
  - py.test --verbose --cov

after_success:
  - coveralls
