name: app
dependencies:
- flask=0.11
- ipython=5.1               # [dev]
- psycopg2=2.6
- python=3.5
- sqlalchemy=1.0
- pip:
  - flake8                  # [test]
  - flake8-import-order     # [test]
  - flask-sqlalchemy>=2.1
  - pdbpp                   # [dev]
  - pgcli                   # [dev]
  - pytest                  # [test]
  - pytest-cov              # [test]
