CREATE USER adi WITH PASSWORD 'adi';
CREATE DATABASE app;
GRANT CONNECT ON DATABASE app TO adi;
GRANT ALL ON DATABASE app TO adi;

CREATE DATABASE app_test;
GRANT CONNECT ON DATABASE app_test TO adi;
GRANT ALL ON DATABASE app_test TO adi;
